config/routes.rb
NCW::Application.routes.draw do
  get "customers/create"

  get "sign_up/index"

  get "sign_up/create"

  get "sign_up/new"

  get "main/index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  resources :customers

   root :to => 'main#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	validates_presence_of :name
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	mount_uploader :image, ImageUploader
	
	validates_presence_of :name,:model_no,:feature,:offer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def create
  	@customer = Customer.create!(params[:customer])
  	redirect_to :root
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@product = Product.all
  end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  def index
  end

  def create
  end

  def new
  	@customer = Customer.new()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NCW</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/_feature_product.html.erb
<h1>Feature Product</h1>
<% @product.each do |t|%>
	<% if t.feature==true%>
		<div>
    	<div>
      	<%= image_tag "#{t.image}"%>
      </div>
      <p>Brand Name:<%=t.name%></p>
    	<p>Model no:<%=t.model_no%></p>
      <input type="button" value="buy now" class="buy"/>
     </div>
	<%end%>
<%end%>

app/views/main/_offer_product.html.erb
<h2>Product with offer</h2>
<% @product.each do |t|%>
	<% if t.offer==true%>
		<div class="turnover">
    	<div class="turnover_image">
      	<%= image_tag "#{t.image}"%>
      </div>
      <p>Brand Name:<%=t.name%></p>
    	<p>Model no:<%=t.model_no%></p>
      <input type="button" value="buy now" class="buy"/>
     </div>
	<%end%>
<%end%>

app/views/main/index.html.erb
<%= link_to "Sign-Up",sign_up_new_path%>
<%= render 'feature_product'%>
<%= render 'offer_product'%>

app/views/sign_up/create.html.erb
<h1>SignUp#create</h1>
<p>Find me in app/views/sign_up/create.html.erb</p>

app/views/sign_up/new.html.erb
<%= form_for @customer  do |t|%>
	<%= t.label:email%>
	<%= t.text_field:email%></br>
	<%= t.label:password%>
	<%= t.password_field:password%></br>
	<%= t.submit "Sign Up"%>
<%end%>